### ISSUE TITLE
Proposal/s: compressing messages, URIs for nodes, and how they relate

### ISSUE THREAD

**Issue by ChanceNCounter** [JarbasHiveMind/HiveMind-core#14]
Important preface: I'm talking about messages exchanged within or between hives *after* a node has established an open socket with master. These are the functional messages consumed and delimited by things like `some_stream.readUntil()`.

The notion is in the early phases, but I'm interested in compressing most/all messages into as few bits as possible. Any message that carries a proper payload will be as long as it is, not much to be done there, but most *instructions* can be whittled down to opcodes, provided we use a large enough space for opcodes to allow for expansion.

I've become fairly comfortable manipulating bitstrings - `pip install bitstring`! `bitstring.BitStream` is exactly what it sounds like - and it's easier than people seem to assume to write bindings for stuff like this. You don't have to be any good with binary. You only have to care about which bits represent which operations. Pick a thing that lets you manipulate bits like strings, pad the end product, turn it back into a bytes object, and you've written the smallest possible version of your protocol. Nothing to it, and you know from the outset that you can transmit over serial without modifying the spec.

There's a [provisional URI scheme](https://www.iana.org/assignments/uri-schemes/prov/iotdisco.pdf) for IoT devices. The first example appears to use, conveniently, AES keys (or 16 chars, at any rate.)

The overwhelming majority of nodes are "internal" to a private hive. Indeed, it might turn out that most personal or LAN hives operate under a single master's jurisdiction, or a small number of masters each belonging to an individual within a household (for example.)

If each node, of any type, is assigned a URI, "full" information could be used for addressing purposes in larger hives. However, the smaller a hive gets, the fewer characters we'd need for addressing. Delimit them with a null character, for all anybody cares, and we end up with a couple bytes for addressing, a couple bytes for issuing instructions, and a couple of those instructions are things like `ADDRESS\0PREP FOR PAYLOAD\0\0`

Thoughts/objections?

**Comment by ChanceNCounter** [comment]
If it has to be broadcast, to avoid ambiguity, it could go `ADDRESS\0INSTRUCTION\0ADDRESS\0\0`

It also doesn't have to be the null character, it's not like that saves space. It's just *extremely* unlikely to occur in a payload.

**Comment by ChanceNCounter** [comment]
This is pretty arbitrary, but illustrates the point:

![IMG20201110143734](https://user-images.githubusercontent.com/2975131/98742071-a5c74800-2362-11eb-86e0-5af182a33990.jpg)

Instead of sending text, instructions take up a few bits, and they don't need padding. Only the final, shoved-together message needs padding. You can't transmit less than a byte at a time over wss, but you can read less than a byte at a time once you've received them.

**Comment by JarbasAl** [comment]
initial implementation in  https://github.com/JarbasHiveMind/hivemind_websocket_client/pull/4
