### ISSUE TITLE
Detect presence or installation of skill-HiveMind and refuse to coexist with it

### ISSUE THREAD

**Issue by ChanceNCounter** [JarbasHiveMind/HiveMind-core#22]
Include instructions for users to create a second hive using the same Mycroft, but make sure they do it in a different environment and etc.

**Comment by JarbasAl** [comment]
closing this one as out of scope, its up for the skill to handle this fully, core should not care if the skill exists and never refuse to launch, the skill should be able to launch several masters in different ports even

the only situation this should happen is if the port is busy, which throws an exception already

companion issue in skill repo stays open for discussion around this
