### ISSUE TITLE
Dep issues

### ISSUE THREAD

**Issue by ChanceNCounter** [JarbasHiveMind/HiveMind-core#35]
#34 reminded me that we should write down the deps that need fixing. This applies to all repos, but a central list had to go someplace.

`zeroconf` is missing from some repos.

`jarbas_utils` is still present, and in some cases is causing *both* `jarbas_utils` *and* `ovos_utils` to come in. That's off the top of my head. I *think* I recall some unmigrated code in the voice sat.

**Comment by builderjer** [comment]
I had mentioned in the chat that there was a DEP that I had to manually install on my Manjaro machine.
Going through my notes and logs, I believe it was pyasn1

**Comment by builderjer** [comment]
Trying a new install on a Picroft device.  Half way through, I had to manually install libxml2-dev and libxslt1-dev
