### ISSUE TITLE
Does not close port on exit

### ISSUE THREAD

**Issue by builderjer** [JarbasHiveMind/HiveMind-core#36]
When exiting "examples/mycroft_master.py", it does not close the used port.  I have to find it with `ps aux` and kill the process.

I know it's not a major issue, but I hope any I put on here will be welcome.

Thanks guys for your work

**Comment by JarbasAl** [comment]
you are correct that the twisted reactor is not closing properly, i think this has been reported in one of the other repos

It's a somewhat important bug to fix, you can't exit with ctrl+c either

**Comment by JarbasAl** [comment]
with the tornado rewrite this no longer applies
