### ISSUE TITLE
Extract zeroconf into plugin and remove all imports from our other repos

### ISSUE THREAD

**Issue by ChanceNCounter** [JarbasHiveMind/HiveMind-core#42]
Explanation to passersby:

We try to avoid shipping LGPL code with permissively licensed code, because it is unclear whether the linking exception applies to interpreted languages like Python. Although it was the `zeroconf` developers' clear intention that `zeroconf` should be available to permissively-licensed and nonfree projects - because there is literally no other reason whatsoever to choose the LGPL - they were, unfortunately, unaware of the real situation with respect to that license and Python. This is primarily because certain evangelists go from university to university neglecting to mention that the license was written with C in mind and did not account for interpreters *at all*.

Tell your friends: stop licensing interpreted code under the LGPL. It probably doesn't work, and nobody knows for sure because nobody has filed the lawsuit yet.

Hence, here we are, reluctantly extracting a good library from our project, despite the fact that its developers *want* us to be able to use it, just to be on the safe side.

That said, zeroconf isn't leaving! It's just being extracted to a plugin, so that we can distribute code related to that LGPL module *100% separately* from our much larger MIT- and Apache-licensed works.

**Comment by JarbasAl** [comment]
see this great answer for context https://softwareengineering.stackexchange.com/questions/119436/what-does-gpl-with-classpath-exception-mean-in-practice/326325#326325

**Comment by JarbasAl** [comment]
closing, it has been removed from this repo and now lives at https://github.com/JarbasHiveMind/HiveMind-presence

see #49
